# Generated by Django 4.2.7 on 2023-12-18 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_meetingroom_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expected_participans',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='projector',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
